Fix devex loading issue when loading init parameters
Zilliqa/dev-explorer pull request #92
Opened 2022-11-08 10:16 UTC by chetan-zilliqa

When loading the shared library init parameters, devex crashes because of a missing condition.

Missing condition - 
To check if the value returned through the API is an object rather than a string. Calling trim() on the string was causing errors.

2022-11-08 10:32 UTC, troelsfr approved these changes
LGTM

2022-11-08 10:44 UTC, JamesHinshelwood approved these changes

2022-11-08 10:45 UTC, merged

2022-11-09 04:05 UTC, yaron-zilliqa requested changes

2022-11-09 04:05 UTC, yaron-zilliqa commented on src/components/DetailsPages/Misc/InfoTabs/InitParamsTab.tsx
> +            <td>{param.value !== undefined ?
This whole block is just unreadable given the number of ternary operators.
Given the (bad) indentation, it's also unclear what some of those operators relate to, e.g.:
`param.value !== undefined ? ... :Array.isArray(param.value) ? param.value.map((x, index) => (`
              
Is it possible to fix this? ideally move some of those blocks into separate functions?